version: '3.5'

services:
  prvd-postgres:
    image: postgres
    container_name: prvd-postgres
    environment:
      - POSTGRES_DB=prvd
      - POSTGRES_USER=prvd
      - POSTGRES_PASSWORD=prvdp455
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "prvd", "-d", "prvd"]
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: prvd-postgres
    volumes:
      - prvd-db:/var/lib/postgresql/data
    networks:
      - prvd
    ports:
      - 5432:5432
    restart: always

  prvd-redis:
    image: redis
    container_name: prvd-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: prvd-redis
    networks:
      - prvd
    ports:
      - 6379:6379
    restart: always

  prvd-nats:
    image: provide/nats-server
    container_name: prvd-nats
    command: ["-auth", "testtoken", "-p", "4222", "-D", "-V"]
    environment:
      JWT_SIGNER_PUBLIC_KEY: |-
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAullT/WoZnxecxKwQFlwE
        9lpQrekSD+txCgtb9T3JvvX/YkZTYkerf0rssQtrwkBlDQtm2cB5mHlRt4lRDKQy
        EA2qNJGM1Yu379abVObQ9ZXI2q7jTBZzL/Yl9AgUKlDIAXYFVfJ8XWVTi0l32Vsx
        tJSd97hiRXO+RqQu5UEr3jJ5tL73iNLp5BitRBwa4KbDCbicWKfSH5hK5DM75EyM
        R/SzR3oCLPFNLs+fyc7zH98S1atglbelkZsMk/mSIKJJl1fZFVCUxA+8CaPiKbpD
        QLpzydqyrk/y275aSU/tFHidoewvtWorNyFWRnefoWOsJFlfq1crgMu2YHTMBVtU
        SJ+4MS5D9fuk0queOqsVUgT7BVRSFHgDH7IpBZ8s9WRrpE6XOE+feTUyyWMjkVgn
        gLm5RSbHpB8Wt/Wssy3VMPV3T5uojPvX+ITmf1utz0y41gU+iZ/YFKeNN8WysLxX
        AP3Bbgo+zNLfpcrH1Y27WGBWPtHtzqiafhdfX6LQ3/zXXlNuruagjUohXaMltH+S
        K8zK4j7n+BYl+7y1dzOQw4CadsDi5whgNcg2QUxuTlW+TQ5VBvdUl9wpTSygD88H
        xH2b0OBcVjYsgRnQ9OZpQ+kIPaFhaWChnfEArCmhrOEgOnhfkr6YGDHFenfT3/RA
        PUl1cxrvY7BHh4obNa6Bf8ECAwEAAQ==
        -----END PUBLIC KEY-----
    healthcheck:
      test: ["CMD", "/usr/local/bin/await_tcp.sh", "localhost:4222"]
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: prvd-nats
    networks:
      - prvd
    ports:
      - 4221:4221
      - 4222:4222
    restart: always
    volumes:
      - ./ops/await_tcp.sh:/usr/local/bin/await_tcp.sh:cached

  prvd-nats-streaming:
    image: provide/nats-streaming
    command: ["-cid", "provide", "--auth", "testtoken", "-SDV"]
    container_name: prvd-nats-streaming
    depends_on:
      - prvd-nats
    healthcheck:
      test: ["CMD", "/usr/local/bin/await_tcp.sh", "localhost:4222"]
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: prvd-nats-streaming
    networks:
      - prvd
    restart: always
    volumes:
      - ./ops/await_tcp.sh:/usr/local/bin/await_tcp.sh:cached

  prvd-vault:
    image: provide/vault
    container_name: prvd-vault
    depends_on:
      - prvd-postgres
    environment:
      - DATABASE_HOST=prvd-postgres
      - DATABASE_NAME=vault_dev
      - DATABASE_USER=vault
      - DATABASE_PASSWORD=vault
      - LOG_LEVEL=DEBUG
      - PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://prvd-vault:8080/status"]
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: prvd-vault
    networks:
      - prvd
    ports:
      - 8082:8080
    restart: always

  prvd-ident:
    image: provide/ident
    container_name: prvd-ident
    depends_on:
      - prvd-nats-streaming
      - prvd-postgres
      - prvd-redis
    environment:
      - DATABASE_HOST=prvd-postgres
      - DATABASE_NAME=ident_dev
      - DATABASE_USER=ident
      - DATABASE_PASSWORD=ident
      - JWT_AUTHORIZATION_AUDIENCE=http://localhost:8081/api/v1
      - NATS_CLIENT_PREFIX=prvd-ident
      - NATS_URL=nats://prvd-nats:4222
      - NATS_STREAMING_URL=nats://prvd-nats-streaming:4222
      - REDIS_HOSTS=prvd-redis:6379
      - LOG_LEVEL=DEBUG
      - PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://prvd-ident:8080/status"]
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: prvd-ident
    networks:
      - prvd
    ports:
      - 8081:8080
    restart: always

  prvd-ident-consumer:
    image: provide/ident
    entrypoint: ./ops/run_consumer.sh
    container_name: prvd-ident-consumer
    depends_on:
      - prvd-nats-streaming
      - prvd-postgres
      - prvd-redis
    environment:
      - CONSUME_NATS_STREAMING_SUBSCRIPTIONS=true
      - DATABASE_HOST=prvd-postgres
      - DATABASE_NAME=ident_dev
      - DATABASE_USER=ident
      - DATABASE_PASSWORD=ident
      - LOG_LEVEL=DEBUG
      - NATS_CLIENT_PREFIX=prvd-ident-consumer
      - NATS_URL=nats://prvd-nats:4222
      - NATS_STREAMING_URL=nats://prvd-nats-streaming:4222
      - PORT=8080
      - REDIS_HOSTS=prvd-redis:6379
      - VAULT_API_SCHEME=http
      - VAULT_API_HOST=prvd-vault:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://prvd-ident:8080/status"]
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: prvd-ident-consumer
    networks:
      - prvd
    restart: always

  prvd-nchain:
    image: provide/nchain
    container_name: prvd-nchain
    depends_on:
      - prvd-nats-streaming
      - prvd-postgres
      - prvd-redis
    environment:
      - DATABASE_HOST=prvd-postgres
      - DATABASE_NAME=nchain_dev
      - DATABASE_USER=nchain
      - DATABASE_PASSWORD=nchain
      - LOG_LEVEL=DEBUG
      - NATS_CLIENT_PREFIX=prvd-nchain
      - NATS_URL=nats://prvd-nats:4222
      - NATS_STREAMING_URL=nats://prvd-nats-streaming:4222
      - PORT=8080
      - REDIS_HOSTS=prvd-redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://prvd-nchain:8080/status"]
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: prvd-nchain
    networks:
      - prvd
    ports:
      - 8080:8080
    restart: always

  prvd-nchain-consumer:
    image: provide/nchain
    entrypoint: ./ops/run_consumer.sh
    container_name: prvd-nchain-consumer
    depends_on:
      - prvd-nats-streaming
      - prvd-postgres
      - prvd-redis
    environment:
      - CONSUME_NATS_STREAMING_SUBSCRIPTIONS=true
      - DATABASE_HOST=prvd-postgres
      - DATABASE_NAME=nchain_dev
      - DATABASE_USER=nchain
      - DATABASE_PASSWORD=nchain
      - LOG_LEVEL=DEBUG
      - NATS_CLIENT_PREFIX=prvd-nchain-consumer
      - NATS_URL=nats://prvd-nats:4222
      - NATS_STREAMING_URL=nats://prvd-nats-streaming:4222
      - NATS_TOKEN=testtoken
      - REDIS_HOSTS=prvd-redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://prvd-nchain:8080/status"]
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: prvd-nchain-consumer
    networks:
      - prvd
    restart: always

  prvd-reachabilitydaemon:
    image: provide/nchain
    entrypoint: ./ops/run_reachabilitydaemon.sh
    container_name: prvd-reachabilitydaemon
    depends_on:
      - prvd-nats-streaming
      - prvd-postgres
      - prvd-redis
    environment:
      - DATABASE_HOST=prvd-postgres
      - DATABASE_NAME=nchain_dev
      - DATABASE_USER=nchain
      - DATABASE_PASSWORD=nchain
      - LOG_LEVEL=DEBUG
      - NATS_CLIENT_PREFIX=reachabilitydaemon
      - NATS_URL=nats://prvd-nats:4222
      - NATS_STREAMING_URL=nats://prvd-nats-streaming:4222
      - REDIS_HOSTS=prvd-redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://prvd-nchain:8080/status"]
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: prvd-reachabilitydaemon
    networks:
      - prvd
    restart: always

  prvd-statsdaemon:
    image: provide/nchain
    entrypoint: ./ops/run_statsdaemon.sh
    container_name: prvd-statsdaemon
    depends_on:
      - prvd-nats-streaming
      - prvd-postgres
      - prvd-redis
    environment:
      - DATABASE_HOST=prvd-postgres
      - DATABASE_NAME=nchain_dev
      - DATABASE_USER=nchain
      - DATABASE_PASSWORD=nchain
      - LOG_LEVEL=DEBUG
      - NATS_CLIENT_PREFIX=statsdaemon
      - NATS_URL=nats://prvd-nats:4222
      - NATS_STREAMING_URL=nats://prvd-nats-streaming:4222
      - REDIS_HOSTS=prvd-redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://prvd-nchain:8080/status"]
      interval: 1m
      timeout: 1s
      retries: 2
      start_period: 10s
    hostname: prvd-statsdaemon
    networks:
      - prvd
    restart: always

networks:
  prvd:
    driver: bridge
    ipam:
      config:
      - subnet: 172.100.0.0/24

volumes:
  prvd-db:

